package IDL;


/**
* IDL/EventManagementIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/schen/git/repository/COMP6231/COMP6231_Project_2/COMP6231_Project_2/src/EventManagementIDL.idl
* Friday, July 19, 2019 3:02:31 o'clock PM EDT
*/

public interface EventManagementIDLOperations 
{
  boolean addEvent (String managerID, String eventID, String eventType, int bookingCapacity);
  boolean removeEvent (String managerID, String eventID, String eventType);
  String[] listEventAvailability (String managerID, String eventType);
  String[] bookEvent (String customerId, String eventId, String eventType);
  String[] cancelEvent (String customerId, String eventId, String eventType);
  String[] getBookingSchedule (String customerId);
  String[] swapEvent (String customerId, String newEventId, String newEventType, String oldEventId, String oldEventType);
  void shutdown ();
} // interface EventManagementIDLOperations
