package IDL;


/**
* IDL/EventManagementIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/schen/git/repository/COMP6231/COMP6231_Project_2/COMP6231_Project_2/src/EventManagementIDL.idl
* Friday, July 19, 2019 3:02:31 o'clock PM EDT
*/

public interface EventManagementIDL extends EventManagementIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventManagementIDL
