package EventManagementIDLApp;


/**
* EventManagementIDLApp/EventManagementIDLHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/zakiyajafrin/Documents/COMP6231-DS/CORBA_Assignment/src/EventManagementIDL.idl
* Wednesday, July 10, 2019 12:54:52 o'clock PM EDT
*/


//    typedef sequence<string> KeyValSeq;
abstract public class EventManagementIDLHelper
{
  private static String  _id = "IDL:EventManagementIDLApp/EventManagementIDL:1.0";

  public static void insert (org.omg.CORBA.Any a, EventManagementIDLApp.EventManagementIDL that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EventManagementIDLApp.EventManagementIDL extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EventManagementIDLApp.EventManagementIDLHelper.id (), "EventManagementIDL");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EventManagementIDLApp.EventManagementIDL read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EventManagementIDLStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EventManagementIDLApp.EventManagementIDL value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EventManagementIDLApp.EventManagementIDL narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventManagementIDLApp.EventManagementIDL)
      return (EventManagementIDLApp.EventManagementIDL)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventManagementIDLApp._EventManagementIDLStub stub = new EventManagementIDLApp._EventManagementIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EventManagementIDLApp.EventManagementIDL unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventManagementIDLApp.EventManagementIDL)
      return (EventManagementIDLApp.EventManagementIDL)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventManagementIDLApp._EventManagementIDLStub stub = new EventManagementIDLApp._EventManagementIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
