package EventManagementIDLApp;


/**
* EventManagementIDLApp/EventManagementIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/zakiyajafrin/Documents/COMP6231-DS/CORBA_Assignment/src/EventManagementIDL.idl
* Wednesday, July 10, 2019 12:54:52 o'clock PM EDT
*/


//    typedef sequence<string> KeyValSeq;
public interface EventManagementIDLOperations 
{
  boolean addEvent (String managerID, String eventID, String eventType, int bookingCapacity);
  boolean removeEvent (String managerID, String eventID, String eventType);
  String[] listEventAvailability (String managerID, String eventType);
  String[] bookEvent (String customerId, String eventId, String eventType);
  String[] cancelEvent (String customerId, String eventId);
  String[] getBookingSchedule (String customerId);
  String[] swapEvent (String customerId, String newEventId, String newEventType, String oldEventId, String oldEventType);

  //	    boolean AddUser(in string ID);
  void shutdown ();
} // interface EventManagementIDLOperations
