package EventManagementIDLApp;


/**
* EventManagementIDLApp/KeyVal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/zakiyajafrin/Documents/COMP6231-DS/CORBA_Assignment/src/EventManagementIDL.idl
* Monday, July 8, 2019 3:20:11 o'clock AM EDT
*/

public final class KeyVal implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public int value = (int)0;

  public KeyVal ()
  {
  } // ctor

  public KeyVal (String _key, int _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class KeyVal
