package EventManagementIDLApp;

/**
* EventManagementIDLApp/KeyValHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/zakiyajafrin/Documents/COMP6231-DS/CORBA_Assignment/src/EventManagementIDL.idl
* Monday, July 8, 2019 3:20:11 o'clock AM EDT
*/

public final class KeyValHolder implements org.omg.CORBA.portable.Streamable
{
  public EventManagementIDLApp.KeyVal value = null;

  public KeyValHolder ()
  {
  }

  public KeyValHolder (EventManagementIDLApp.KeyVal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EventManagementIDLApp.KeyValHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EventManagementIDLApp.KeyValHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EventManagementIDLApp.KeyValHelper.type ();
  }

}
