package EventManagementIDLApp;


/**
* EventManagementIDLApp/ResultListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/zakiyajafrin/Documents/COMP6231-DS/CORBA_Assignment/src/EventManagementIDL.idl
* Wednesday, July 10, 2019 12:54:52 o'clock PM EDT
*/

public final class ResultListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ResultListHolder ()
  {
  }

  public ResultListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EventManagementIDLApp.ResultListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EventManagementIDLApp.ResultListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EventManagementIDLApp.ResultListHelper.type ();
  }

}
